//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesilmaviMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class clcard
    {
        public long LOGICALREF { get; set; }
        public int ACTIVE { get; set; }
        public int CARDTYPE { get; set; }
        public string CODE { get; set; }
        public string DEFINITION_ { get; set; }
        public string CYPHCODE { get; set; }
        public string ADDR1 { get; set; }
        public string ADDR2 { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string TELNRS1 { get; set; }
        public string TELNRS2 { get; set; }
        public string FAXNR { get; set; }
        public string TAXNR { get; set; }
        public string TAXOFFICE { get; set; }
        public string INCHARGE { get; set; }
        public string EMAILADDR { get; set; }
        public string TOWN { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<float> DISCRATE { get; set; }
        public Nullable<int> PAYMENTREF { get; set; }
        public Nullable<decimal> RISKTOTAL { get; set; }
        public Nullable<decimal> ACCRISKTOTAL { get; set; }
        public Nullable<decimal> ACCRISKLIMIT { get; set; }
        public Nullable<decimal> ACCRISKBALANCED { get; set; }
        public Nullable<decimal> ACCCOLLATERAL { get; set; }
        public Nullable<decimal> CEK0_DEBIT { get; set; }
        public Nullable<decimal> CEK1_DEBIT { get; set; }
        public Nullable<decimal> SENET0_DEBIT { get; set; }
        public Nullable<decimal> SENET1_DEBIT { get; set; }
        public Nullable<decimal> CSTCSRISKTOTAL { get; set; }
        public Nullable<decimal> CSTCSRISKLIMIT { get; set; }
        public Nullable<short> RISKTYPES1 { get; set; }
        public string SPECODE { get; set; }
        public string SPECODE2 { get; set; }
        public string SPECODE3 { get; set; }
        public string SPECODE4 { get; set; }
        public string SPECODE5 { get; set; }
        public Nullable<bool> NEED_PASS_CHANGE { get; set; }
        public string ITEM_GROUP_SECURITY { get; set; }
        public bool IS_SUPPLIER { get; set; }
        public short INVENNO { get; set; }
        public string USERNAME { get; set; }
        public bool IS_LICENCED { get; set; }
        public string USER_MAIL { get; set; }
        public Nullable<bool> SIPARIS_VEREBILIR { get; set; }
        public Nullable<int> MIN_SIPARIS_TUTAR { get; set; }
        public string STATIC_IP { get; set; }
        public Nullable<long> PARENTCLREF { get; set; }
        public string XML_IP { get; set; }
        public string TRADINGGRP { get; set; }
        public Nullable<bool> VADE_KONTROLU_YAPMA { get; set; }
        public string LOGOURL { get; set; }
        public short CRM_DURUM { get; set; }
    }
}
