//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesilmaviMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public int LOGICALREF { get; set; }
        public Nullable<short> CARDTYPE { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public float VAT { get; set; }
        public Nullable<int> PAYMENTREF { get; set; }
        public bool ACTIVE { get; set; }
        public string STGRPCODE { get; set; }
        public string PRODUCERCODE { get; set; }
        public bool CANCONFIGURE { get; set; }
        public string MAKE { get; set; }
        public string UNIT { get; set; }
        public string UNIT2 { get; set; }
        public float UNITCONVERTRATE { get; set; }
        public int UNITSETREF { get; set; }
        public float AMOUNT_IN_STOK { get; set; }
        public Nullable<decimal> ACTIVE_SALES_ORDER { get; set; }
        public Nullable<float> ACTIVE_PURCHASE_ORDER { get; set; }
        public Nullable<float> SAFE_LEVEL { get; set; }
        public string BARCODE { get; set; }
        public string SPECODE { get; set; }
        public string SPECODE2 { get; set; }
        public string SPECODE3 { get; set; }
        public string SPECODE4 { get; set; }
        public string SPECODE5 { get; set; }
        public string TAGS { get; set; }
        public Nullable<short> EXTACCESSFLAGS { get; set; }
        public Nullable<bool> SHOW_IN_VITRIN { get; set; }
        public Nullable<bool> SHOW_IN_HAFTANIN_URUNU { get; set; }
        public Nullable<float> PUAN_FIYAT_CARPAN { get; set; }
        public Nullable<short> PUAN_YENI_URUN_TIP { get; set; }
        public Nullable<int> PUAN_YENI_URUN_SABIT_PUAN { get; set; }
        public Nullable<float> PUAN_YENI_URUN_FIYAT_CARPAN { get; set; }
        public string DETAIL_TEXT { get; set; }
        public int MIN_SIPARIS_MIKTAR { get; set; }
        public bool MIN_SIPARIS_MIKTAR_BOLUNEMEZ { get; set; }
        public string NAME3 { get; set; }
        public string NAME4 { get; set; }
        public string B2CCODE { get; set; }
        public string DETAIL_HTML { get; set; }
        public Nullable<int> HAFTANIN_URUNU_SIRA { get; set; }
        public Nullable<float> ADDTAXRATE { get; set; }
        public Nullable<float> ADDTAXAMOUNT { get; set; }
        public Nullable<bool> EFFECTKDV { get; set; }
        public Nullable<decimal> EXTRACOSTFACTOR { get; set; }
        public string EXTRACOSTITEMCODE { get; set; }
        public string EXTRACOSTEXCCLIENTS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> ACTIVATED_DATE { get; set; }
        public Nullable<decimal> UNITCOST { get; set; }
    }
}
