//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesilmaviMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class setup
    {
        public long id { get; set; }
        public string firma_ismi { get; set; }
        public string firma_adres { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string fax1 { get; set; }
        public string fax2 { get; set; }
        public string email { get; set; }
        public long pesin_payplanref { get; set; }
        public long vadeli_payplanref { get; set; }
        public string logoPath { get; set; }
        public string msn_invitee { get; set; }
        public bool sabit_iskonto { get; set; }
        public bool odeme_plani_iskonto { get; set; }
        public bool satis_elemani_ozel_fiyat { get; set; }
        public string iletisim_html { get; set; }
        public bool satis_elemani_kdv_degistirme { get; set; }
        public Nullable<short> siparis_odeme_plani_tipi { get; set; }
        public bool sanal_pos { get; set; }
        public string sozlesme_html { get; set; }
        public Nullable<bool> musteri_fatura_aciklamasi_goster { get; set; }
        public Nullable<bool> satis_elemani_hesap_makinasi_goster { get; set; }
        public Nullable<bool> musteri_fatura_detay_goster { get; set; }
        public Nullable<bool> dovizli_fiyatlari_cevir { get; set; }
        public Nullable<bool> guvenli_stok_seviyesi_kontrolu_yap { get; set; }
        public string send_mail_server { get; set; }
        public string send_mail { get; set; }
        public string send_mail_password { get; set; }
        public string banka_html { get; set; }
        public bool siparis_mail_gonder { get; set; }
        public string siparis_mail_alicilar { get; set; }
        public bool siparis_iptal_mail_gonder { get; set; }
        public string siparis_iptal_mail_alicilar { get; set; }
        public bool tahsilat_mail_gonder { get; set; }
        public string tahsilat_mail_alicilar { get; set; }
        public decimal senet_masraf_tutar { get; set; }
        public decimal kargo_alt_limit { get; set; }
        public decimal kargo_ucreti { get; set; }
        public decimal kapida_odeme_kargo_alt_limit { get; set; }
        public decimal kapida_odeme_kargo_ucreti { get; set; }
        public Nullable<bool> cari_kargo_ucreti_hesaplama { get; set; }
    }
}
