//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesilmaviMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class slsman
    {
        public long LOGICALREF { get; set; }
        public string CODE { get; set; }
        public string DEFINITION_ { get; set; }
        public string SPECODE { get; set; }
        public string CYPHCODE { get; set; }
        public long ACTIVE { get; set; }
        public string PASSWORD { get; set; }
        public bool IS_SUPERVISOR { get; set; }
        public Nullable<bool> IS_SUPERSLSMAN { get; set; }
        public Nullable<bool> CAN_USE_VPOS { get; set; }
        public string MAKBUZ_NO_PREFIX { get; set; }
        public Nullable<int> MAKBUZ_NO_LAST { get; set; }
        public string ITEM_GROUP_SECURITY { get; set; }
        public Nullable<short> INVENNO { get; set; }
        public short SLSMAN_TYPE { get; set; }
        public Nullable<int> RELATED_CLIENTREF { get; set; }
        public bool IS_LICENCED { get; set; }
        public bool FAIZ_UYGULANSINMI { get; set; }
        public string PICTURE_URL { get; set; }
        public string TELNUMBER { get; set; }
        public string STATIC_IP { get; set; }
        public string EMAIL_ADDR { get; set; }
        public Nullable<int> PRCLIST_PRIORITY { get; set; }
    }
}
