//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesilmaviMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sync_log
    {
        public int Id { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Islem { get; set; }
        public string Seviye { get; set; }
        public string Logger { get; set; }
        public string Mesaj { get; set; }
        public string Hata { get; set; }
    }
}
