//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesilmaviMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sync_config
    {
        public string Anahtar { get; set; }
        public string Deger { get; set; }
    }
}
