//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesilmaviMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class virtualpos
    {
        public int VPOSREF { get; set; }
        public string CODE { get; set; }
        public Nullable<int> BANKACCREF { get; set; }
        public string SHOPNO { get; set; }
        public string TERMINALNO { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string STOREKEY { get; set; }
        public string IMAGEURL { get; set; }
        public string APIGATEURL { get; set; }
        public string D3GATEURL { get; set; }
        public string QUERYTRANSURL { get; set; }
        public Nullable<float> VADEFARKI { get; set; }
        public Nullable<bool> IS3D { get; set; }
        public Nullable<bool> ISPOSNET { get; set; }
        public Nullable<bool> ISGARANTI { get; set; }
        public Nullable<bool> ISIPAY { get; set; }
        public Nullable<bool> ISORTAKODEME { get; set; }
        public Nullable<bool> ISVAKIF { get; set; }
        public Nullable<bool> ISKUVEYT { get; set; }
        public Nullable<bool> ISVPOSQNBFINANSBANK { get; set; }
        public Nullable<bool> DEFAULTVPOS { get; set; }
        public string FLAGS { get; set; }
        public string PAYPLANCODE { get; set; }
        public string ANARENK { get; set; }
        public Nullable<bool> TEKCEKIMVARMI { get; set; }
        public string BINEXTRA { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    }
}
